### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by NateHand93** [paromita-d/project-library#4]
Alright, I'm going to be ultra nit-picky with this, but here's some preliminary feedback.

- No need to reference the package name of the Main class here:
https://github.com/paromita-d/project-library/blob/a88ecb95d4c8595ef9a68a2ffff610a8057c8551/library-be/src/main/java/org/library/Main.java#L9

- The one benefit of using constructor injection is that it allows you to mark your dependencies as _final_. Change this to `private final MetaDataService metaDataService;`:
https://github.com/paromita-d/project-library/blob/a88ecb95d4c8595ef9a68a2ffff610a8057c8551/library-be/src/main/java/org/library/controller/AdminController.java#L21

- It's good to see that you're creating custom exception handlers for your endpoints. One thing though: your `LibraryException` is most likely caused by _client-side_ errors rather than _server-side_ errors. One such example I found was a user trying to enter a negative checkout duration. These errors should cause your controllers to return 4XX status codes instead of 5XX status codes
https://github.com/paromita-d/project-library/blob/a88ecb95d4c8595ef9a68a2ffff610a8057c8551/library-be/src/main/java/org/library/exception/LibraryErrorAdvice.java#L21-L35

- Catch-all try/catch blocks like this are generally considered a code smell. Generally (and I stress, _generally_)  avoid wrapping multiple lines of code in a try/catch block that catches any exception. If there is a specific runtime exception that you are trying to catch here (maybe a DB-related exception), be specific and only catch that particular exception.
https://github.com/paromita-d/project-library/blob/a88ecb95d4c8595ef9a68a2ffff610a8057c8551/library-be/src/main/java/org/library/service/MetaDataService.java#L39-L50

Overall, good start! I couldn't find many issues with this code. Your code formatting is good and your code organization is very logical. Your tests also went above and beyond, as all of your tests actually spin up an H2 database and test your repositories instead of mocking them. Next time you contribute code to this repo, make a pull request, and I can review it. Nice start!

**Comment by paromita-d** [comment]
closing issue since this has been addressed in the PR
